import 'dotenv/config'
import { prisma } from '../src/lib/prisma'

function extractTitleFromUrl(url: string): string {
  try {
    const parsed = new URL(url)
    const hostname = parsed.hostname.replace(/^www\./, '')
    
    // Extract meaningful parts
    const pathParts = parsed.pathname.split('/').filter(Boolean)
    
    if (pathParts.length > 0) {
      // Use last meaningful path segment + domain
      const lastPart = pathParts[pathParts.length - 1]
      // Convert kebab-case to Title Case
      const titleCase = lastPart
        .split('-')
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' ')
      return `${hostname.split('.')[0]} - ${titleCase}`
    }
    
    // Just use domain name
    const domainParts = hostname.split('.')
    return domainParts[0].charAt(0).toUpperCase() + domainParts[0].slice(1)
  } catch {
    // Fallback: use URL as-is
    return url.replace(/^https?:\/\//, '').replace(/\/$/, '')
  }
}

function extractAuthorFromUrl(url: string): string | null {
  try {
    const parsed = new URL(url)
    const hostname = parsed.hostname.replace(/^www\./, '')
    const domainParts = hostname.split('.')
    
    // Use main domain as author (e.g., "stripe" from "stripe.com")
    if (domainParts.length >= 2) {
      return domainParts[0].charAt(0).toUpperCase() + domainParts[0].slice(1)
    }
    
    return null
  } catch {
    return null
  }
}

const sites = [
  'https://stripe.com/en-se',
  'https://factory.ai/',
  'https://www.hyperbolic.ai/',
  'https://www.makingsoftware.com/',
  'https://sunriserobotics.co/',
  'https://www.jonite.com/',
  'https://vwlab.io/pages/report',
  'https://www.apple.com/airpods-pro/',
]

async function main() {
  console.log(`📝 Adding ${sites.length} sites to database...\n`)
  
  let added = 0
  let skipped = 0
  
  for (const url of sites) {
    try {
      // Check if site already exists
      const existing = await prisma.site.findFirst({
        where: { url: url.replace(/\/$/, '') } // Normalize trailing slash
      })
      
      if (existing) {
        console.log(`⏭️  Skipping ${url} (already exists)`)
        skipped++
        continue
      }
      
      const title = extractTitleFromUrl(url)
      const author = extractAuthorFromUrl(url)
      
      console.log(`➕ Adding: ${title}`)
      console.log(`   URL: ${url}`)
      console.log(`   Author: ${author || '(none)'}`)
      
      // Create site (imageUrl will be generated by screenshot service if available)
      const site = await prisma.site.create({
        data: {
          title,
          description: '',
          url: url.replace(/\/$/, ''), // Normalize trailing slash
          imageUrl: null, // Will be generated via screenshot service
          author,
          tags: {
            create: []
          }
        },
      })
      
      console.log(`   ✓ Created site: ${site.id}\n`)
      added++
    } catch (e: any) {
      console.error(`❌ Error adding ${url}:`, e.message || e)
      console.log()
    }
  }
  
  console.log('═'.repeat(60))
  console.log(`✅ Summary:`)
  console.log(`   Added: ${added}`)
  console.log(`   Skipped: ${skipped}`)
  console.log(`   Total: ${sites.length}`)
  console.log('═'.repeat(60))
  console.log(`\n💡 Note: Images will be generated when you call the screenshot service.`)
  console.log(`   The sites API will automatically trigger screenshots on submission.`)
}

main()
  .catch(e => {
    console.error('❌ Fatal error:', e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())

