#!/usr/bin/env tsx
/**
 * Analyze the actual SQL query being generated by Prisma
 * and check if indexes are being used
 */

import 'dotenv/config'
import { prisma } from '../src/lib/prisma'

async function main() {
  try {
    console.log('Analyzing findMany query performance...\n')
    
    // First, let's see what SQL Prisma generates
    console.log('1. Checking query plan with EXPLAIN ANALYZE...\n')
    
    const explainResult = await prisma.$queryRawUnsafe<any[]>(`
      EXPLAIN (ANALYZE, BUFFERS, VERBOSE)
      SELECT "sites"."id", "sites"."title", "sites"."description", "sites"."url", 
             "sites"."imageUrl", "sites"."author", "sites"."createdAt", "sites"."updatedAt"
      FROM "sites"
      ORDER BY "sites"."createdAt" DESC, "sites"."id" ASC
      LIMIT 61;
    `)
    
    console.log('Query Plan:')
    for (const row of explainResult) {
      console.log(row['QUERY PLAN'] || row['query plan'] || row)
    }
    
    console.log('\n2. Checking table statistics...\n')
    const stats = await prisma.$queryRawUnsafe<any[]>(`
      SELECT 
        schemaname,
        relname as tablename,
        n_live_tup as row_count,
        n_dead_tup as dead_rows,
        last_vacuum,
        last_autovacuum,
        last_analyze,
        last_autoanalyze
      FROM pg_stat_user_tables
      WHERE relname = 'sites';
    `)
    
    if (stats.length > 0) {
      console.log('Table Statistics:')
      console.log(`  Row count: ${stats[0].row_count}`)
      console.log(`  Dead rows: ${stats[0].n_dead_tup}`)
      console.log(`  Last analyzed: ${stats[0].last_autoanalyze || stats[0].last_analyze || 'Never'}`)
    }
    
    console.log('\n3. Checking index usage statistics...\n')
    const indexStats = await prisma.$queryRawUnsafe<any[]>(`
      SELECT 
        schemaname,
        relname as tablename,
        indexrelname as indexname,
        idx_scan as index_scans,
        idx_tup_read as tuples_read,
        idx_tup_fetch as tuples_fetched
      FROM pg_stat_user_indexes
      WHERE relname = 'sites'
      ORDER BY indexrelname;
    `)
    
    console.log('Index Usage Statistics:')
    for (const idx of indexStats) {
      console.log(`  ${idx.indexname}:`)
      console.log(`    Scans: ${idx.index_scans}`)
      console.log(`    Tuples read: ${idx.tuples_read}`)
      console.log(`    Tuples fetched: ${idx.tuples_fetched}`)
    }
    
    console.log('\n4. Testing actual query performance...\n')
    const startTime = Date.now()
    const result = await prisma.site.findMany({
      orderBy: [
        { createdAt: 'desc' },
        { id: 'asc' }
      ],
      take: 61,
      skip: 0,
    })
    const endTime = Date.now()
    const duration = endTime - startTime
    
    console.log(`Query executed in ${duration}ms`)
    console.log(`Returned ${result.length} rows`)
    
  } catch (error: any) {
    console.error('Error:', error.message)
    if (error.stack) {
      console.error('Stack:', error.stack)
    }
    process.exit(1)
  } finally {
    await prisma.$disconnect()
  }
}

main()

