// scripts/check_concept_generation_progress.ts
// Check progress of concept generation script

import 'dotenv/config';
import { prisma } from '../src/lib/prisma';
import * as fs from 'fs/promises';
import * as path from 'path';

async function main() {
  console.log('📊 Checking concept generation progress...\n');

  // Get count of sites with images in use
  const activeSites = await prisma.site.findMany({
    where: {
      imageUrl: {
        not: null,
      },
    },
    select: {
      id: true,
      imageUrl: true,
    },
  });

  const totalSitesWithImages = activeSites.length;
  console.log(`📌 Total sites with images: ${totalSitesWithImages}`);

  // Count concepts in database vs seed file
  const dbConcepts = await prisma.concept.count();
  
  let seedConcepts: any[] = [];
  try {
    const seedPath = path.join(process.cwd(), 'src', 'concepts', 'seed_concepts.json');
    const seedContent = await fs.readFile(seedPath, 'utf-8');
    seedConcepts = JSON.parse(seedContent);
  } catch (e: any) {
    console.error(`Error reading seed file: ${e.message}`);
    return;
  }

  const seedConceptCount = seedConcepts.length;
  console.log(`📚 Concepts in database: ${dbConcepts}`);
  console.log(`📄 Concepts in seed file: ${seedConceptCount}`);
  
  // Count new concepts (those not in DB)
  const dbConceptIds = new Set(
    (await prisma.concept.findMany({ select: { id: true } })).map(c => c.id)
  );
  
  const newConcepts = seedConcepts.filter(sc => !dbConceptIds.has(sc.id));
  console.log(`🆕 New concepts (in seed, not in DB): ${newConcepts.length}`);

  // Check if we can estimate progress by looking at recently added concepts
  // Concepts generated by Gemini typically have certain patterns
  const recentConcepts = seedConcepts.slice(-50);
  const geminiGeneratedConcepts = recentConcepts.filter((sc: any) => {
    // New concepts from Gemini generation often don't have embeddings in seed file yet
    // Or we can check by date/pattern
    return true; // For now, assume recent = gemini generated
  }).length;

  console.log(`\n📈 Recent additions (last 50): ${recentConcepts.length} concepts`);

  // Estimate: if we expect ~11 concepts per image (one per category)
  // and we have 158 images, that's ~1738 potential concepts
  // But many will be duplicates/merged
  const expectedConceptsPerImage = 11; // At least one per category
  const totalImages = activeSites.length;
  const expectedTotalNewConcepts = totalImages * expectedConceptsPerImage;
  
  console.log(`\n🎯 Expected concepts:`);
  console.log(`  Images to process: ${totalImages}`);
  console.log(`  Expected new concepts (if all unique): ${expectedTotalNewConcepts}`);
  console.log(`  Actual new concepts: ${newConcepts.length}`);
  console.log(`  Progress estimate: ${((newConcepts.length / expectedTotalNewConcepts) * 100).toFixed(1)}%`);

  // Show some recent new concepts
  if (newConcepts.length > 0) {
    console.log(`\n🆕 Recent new concepts added:`);
    for (const concept of newConcepts.slice(-10)) {
      console.log(`  • ${concept.label} (${concept.category})`);
    }
  }

  // Check if script might still be running
  const lastModified = await fs.stat(path.join(process.cwd(), 'src', 'concepts', 'seed_concepts.json'));
  const timeSinceLastUpdate = Date.now() - lastModified.mtimeMs;
  const minutesSinceUpdate = Math.floor(timeSinceLastUpdate / 60000);
  
  console.log(`\n⏰ Seed file last updated: ${minutesSinceUpdate} minutes ago`);
  
  if (minutesSinceUpdate < 5) {
    console.log(`✅ Script appears to be actively running!`);
  } else if (minutesSinceUpdate < 30) {
    console.log(`⚠️  Script may have finished recently`);
  } else {
    console.log(`ℹ️  Script appears to have finished`);
  }
}

main()
  .then(() => {
    console.log('\n✅ Progress check complete');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Error:', error);
    process.exit(1);
  });

